using System;
using System.Collections.Generic;
using System.Text;

namespace MHWMasterDataUtils.Core
{
    public enum HuntingHornSongEffect
    {
        SelfImprovement = 0,
        AttackUpS = 1,
        AttackUpL = 2,
        HealthBoostS = 3,
        HealthBoostL = 4,
        StaminaUseReducedS = 5,
        StaminaUseReducedL = 6,
        WindPressureNegated = 7,
        AllWindPressureNegated = 8,
        DefenseUpS = 9,
        DefenseUpL = 10,
        ToolUseDrainReducedS = 11,
        ToolUseDrainReducedL = 12,
        HealthRecoveryS = 13,
        HealthRecoveryL = 14,
        HealthRecoverySAntidote = 15,
        HealthRecoveryMAntidote = 16,
        HealthRecoveryM1 = 17,
        RecoverySpeedS = 18,
        RecoverySpeedL = 19,
        EarplugsS = 20,
        EarplugsL = 21,
        DivineProtection = 22,
        ScoutflyPowerUp = 23,
        EnvironmentDamageNegated = 24,
        StunNegated = 25,
        ParalysisNegated = 26,
        TremorsNegated = 27,
        MuckRes = 28,
        FireResBoostS = 29,
        FireResBoostL = 30,
        WaterResBoostS = 31,
        WaterResBoostL = 32,
        ThunderResBoostS = 33,
        ThunderResBoostL = 34,
        IceResBoostS = 35,
        IceResBoostL = 36,
        DragonResBoostS = 37,
        DragonResBoostL = 38,
        ElementalAttackBoost = 39,
        AllMelodyEffectsExtended = 40,
        SonicWaves = 41,
        AttackDefenseUpS = 42,
        KnockbacksNegated = 43,
        AllAilmentsNegated = 44,
        BlightResUp = 45,
        AffinityUpHealthRecoveryS = 46,
        BlightNegated = 47,
        EarplugsSWindPressureNegated = 48,
        AbnormalStatusAttackIncreased = 49,
        HealthRecoveryM2 = 50
    }
}
