using System;
using System.Collections.Generic;
using System.Text;

namespace MHWMasterDataUtils.Weapons.HighLevel
{
    public enum HuntingHornSongEffect
    {
        SelfImprovement,
        AttackUpS,
        AttackUpL,
        HealthBoostS,
        HealthBoostL,
        StaminaUseReducedS,
        StaminaUseReducedL,
        WindPressureNegated,
        AllWindPressureNegated,
        DefenseUpS,
        DefenseUpL,
        ToolUseDrainReducedS,
        ToolUseDrainReducedL,
        HealthRecoveryS,
        HealthRecoveryL,
        HealthRecoverySAntidote,
        HealthRecoveryMAntidote,
        HealthRecoveryM1,
        RecoverySpeedS,
        RecoverySpeedL,
        EarplugsS,
        EarplugsL,
        DivineProtection,
        ScoutflyPowerUp,
        EnvironmentDamageNegated,
        StunNegated,
        ParalysisNegated,
        TremorsNegated,
        MuckRes,
        FireResBoostS,
        FireResBoostL,
        WaterResBoostS,
        WaterResBoostL,
        ThunderResBoostS,
        ThunderResBoostL,
        IceResBoostS,
        IceResBoostL,
        DragonResBoostS,
        DragonResBoostL,
        ElementalAttackBoost,
        AllMelodyEffectsExtended,
        SonicWaves,
        AttackDefenseUpS,
        KnockbacksNegated,
        AllAilmentsNegated,
        BlightResUp,
        AffinityUpHealthRecoveryS,
        BlightNegated,
        EarplugsSWindPressureNegated,
        AbnormalStatusAttackIncreased,
        HealthRecoveryM2
    }
}
